/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.control_citas.proyecto_final;

import java.util.Calendar;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author k285
 */
public class Lista extends javax.swing.JPanel {
    private String[] columnas = {"Fecha", "Hora", "Nombre", "Telefono", "Correo", "Domicilio", "Peinado", "Tinte", "Manicure", "Corte", "Total"};
    private float total = 0f;
    private String fechaCapturada = "";
    private String dia, mes, agno;
    private float totalPeinado = 0f;
    private float totalTinte = 0f;
    private float totalManicure = 0f;
    private float totalCorte = 0f;
    private int filas = 1;    
    private int cantidadFechas = 1;    
    private int indiceFechas = 0;
    private boolean fechaNueva = true;
    private String[][][] fechas = new String[cantidadFechas][filas][11];
    private String[][] data = new String[filas][11];
    
    private String[][] dataCambio = data;
    private boolean banderaFecha, banderaHora, banderaNombre, banderaTotal;
    private String sexoCorte = "Default";
 //   private boolean banderaSexoSeleccionado = false;
    private final float PRECIO_PEINADO1 = 90;
    private final float PRECIO_PEINADO2 = 100;
    private final float PRECIO_PEINADO3 = 110;
    private final float PRECIO_PEINADOD = 0;
    private final float PRECIO_TINTE1 = 80;
    private final float PRECIO_TINTE2 = 120;
    private final float PRECIO_TINTE3 = 140;
    private final float PRECIO_TINTED = 0;
    private final float PRECIO_MANICURE1 = 115;
    private final float PRECIO_MANICURE2 = 130;
    private final float PRECIO_MANICURE3 = 145;
    private final float PRECIO_MANICURED = 0;
    private final float PRECIO_CORTE_MASCULINO1 = 60;
    private final float PRECIO_CORTE_MASCULINO2 = 100;
    private final float PRECIO_CORTE_MASCULINO3 = 111;
    private final float PRECIO_CORTE_MASCULINOD = 0;
    private final float PRECIO_CORTE_FEMENINO1 = 100;
    private final float PRECIO_CORTE_FEMENINO2 = 120;
    private final float PRECIO_CORTE_FEMENINO3 = 130;
    private final float PRECIO_CORTE_FEMENINOD = 0;
    private final float PRECIO_CORTED = 0;
    
    /**
     * Creates new form Lista
     */
    public Lista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoPeinado = new javax.swing.ButtonGroup();
        grupoTinte = new javax.swing.ButtonGroup();
        grupoManicure = new javax.swing.ButtonGroup();
        grupoCorte = new javax.swing.ButtonGroup();
        fechajLabel = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        horajLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        horajComboBox = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        peinadojLabel = new javax.swing.JLabel();
        peinadojRadioButton1 = new javax.swing.JRadioButton();
        peinadojRadioButton2 = new javax.swing.JRadioButton();
        peinadojRadioButton3 = new javax.swing.JRadioButton();
        peinadojRadioButtonD = new javax.swing.JRadioButton();
        tintejRadioButton2 = new javax.swing.JRadioButton();
        tintejRadioButton3 = new javax.swing.JRadioButton();
        tintejRadioButtonD = new javax.swing.JRadioButton();
        tintejLabel = new javax.swing.JLabel();
        tintejRadioButton1 = new javax.swing.JRadioButton();
        manicurejRadioButton2 = new javax.swing.JRadioButton();
        manicurejRadioButton3 = new javax.swing.JRadioButton();
        manicurejRadioButtonD = new javax.swing.JRadioButton();
        manicurejLabel = new javax.swing.JLabel();
        manicurejRadioButton1 = new javax.swing.JRadioButton();
        cortejRadioButtonD = new javax.swing.JRadioButton();
        cortejLabel = new javax.swing.JLabel();
        cortejRadioButton1 = new javax.swing.JRadioButton();
        cortejRadioButton2 = new javax.swing.JRadioButton();
        cortejRadioButton3 = new javax.swing.JRadioButton();
        bloquearjButton = new javax.swing.JButton();
        cortejComboBox = new javax.swing.JComboBox<>();
        jSeparator2 = new javax.swing.JSeparator();
        nombrejLabel = new javax.swing.JLabel();
        nombrejTextField = new javax.swing.JTextField();
        telefonojLabel = new javax.swing.JLabel();
        telefonojTextField = new javax.swing.JTextField();
        correojLabel = new javax.swing.JLabel();
        correojTextField = new javax.swing.JTextField();
        domiciliojLabel = new javax.swing.JLabel();
        domiciliojTextField = new javax.swing.JTextField();
        totaljLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        totaljTextArea = new javax.swing.JTextArea();
        jSeparator3 = new javax.swing.JSeparator();
        eliminarjButton = new javax.swing.JButton();
        agnadirjButton = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(1370, 720));
        setPreferredSize(new java.awt.Dimension(1370, 720));

        fechajLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fechajLabel.setText("Fecha");
        fechajLabel.setPreferredSize(new java.awt.Dimension(13, 14));

        jDateChooser1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jDateChooser1FocusLost(evt);
            }
        });
        jDateChooser1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jDateChooser1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jDateChooser1MousePressed(evt);
            }
        });
        jDateChooser1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jDateChooser1PropertyChange(evt);
            }
        });

        horajLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        horajLabel.setText("Hora");
        horajLabel.setPreferredSize(new java.awt.Dimension(13, 14));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        horajComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "00:00", "00:30", "01:00", "01:30", "02:00", "02:30", "03:00", "03:30", "04:00", "04:30", "05:00", "05:30", "06:00", "06:30", "07:00", "07:30", "08:00", "08:30", "09:00", "09:30", "10:00", "10:30", "11:00", "11:30", "12:00", "12:30", "13:00", "13:30", "14:00", "14:30", "15:00", "15:30", "16:00", "16:30", "17:00", "17:30", "18:00", "18:30", "19:00", "19:30", "20:00", "20:30", "21:00", "21:30", "22:00", "22:30", "23:00", "23:30" }));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Fecha", "Hora", "Nombre", "Telefono", "Correo", "Domicilio", "Peinado", "Tinte", "Manicure", "Corte", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        peinadojLabel.setText("Peinado");

        grupoPeinado.add(peinadojRadioButton1);
        peinadojRadioButton1.setText("1");
        peinadojRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                peinadojRadioButton1ActionPerformed(evt);
            }
        });

        grupoPeinado.add(peinadojRadioButton2);
        peinadojRadioButton2.setText("2");
        peinadojRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                peinadojRadioButton2ActionPerformed(evt);
            }
        });

        grupoPeinado.add(peinadojRadioButton3);
        peinadojRadioButton3.setText("3");
        peinadojRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                peinadojRadioButton3ActionPerformed(evt);
            }
        });

        grupoPeinado.add(peinadojRadioButtonD);
        peinadojRadioButtonD.setSelected(true);
        peinadojRadioButtonD.setText("D");
        peinadojRadioButtonD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                peinadojRadioButtonDActionPerformed(evt);
            }
        });

        grupoTinte.add(tintejRadioButton2);
        tintejRadioButton2.setText("2");
        tintejRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tintejRadioButton2ActionPerformed(evt);
            }
        });

        grupoTinte.add(tintejRadioButton3);
        tintejRadioButton3.setText("3");
        tintejRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tintejRadioButton3ActionPerformed(evt);
            }
        });

        grupoTinte.add(tintejRadioButtonD);
        tintejRadioButtonD.setSelected(true);
        tintejRadioButtonD.setText("D");
        tintejRadioButtonD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tintejRadioButtonDActionPerformed(evt);
            }
        });

        tintejLabel.setText("Tinte");

        grupoTinte.add(tintejRadioButton1);
        tintejRadioButton1.setText("1");
        tintejRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tintejRadioButton1ActionPerformed(evt);
            }
        });

        grupoManicure.add(manicurejRadioButton2);
        manicurejRadioButton2.setText("2");
        manicurejRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manicurejRadioButton2ActionPerformed(evt);
            }
        });

        grupoManicure.add(manicurejRadioButton3);
        manicurejRadioButton3.setText("3");
        manicurejRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manicurejRadioButton3ActionPerformed(evt);
            }
        });

        grupoManicure.add(manicurejRadioButtonD);
        manicurejRadioButtonD.setSelected(true);
        manicurejRadioButtonD.setText("D");
        manicurejRadioButtonD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manicurejRadioButtonDActionPerformed(evt);
            }
        });

        manicurejLabel.setText("Manicure");

        grupoManicure.add(manicurejRadioButton1);
        manicurejRadioButton1.setText("1");
        manicurejRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manicurejRadioButton1ActionPerformed(evt);
            }
        });

        grupoCorte.add(cortejRadioButtonD);
        cortejRadioButtonD.setSelected(true);
        cortejRadioButtonD.setText("D");
        cortejRadioButtonD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cortejRadioButtonDActionPerformed(evt);
            }
        });

        cortejLabel.setText("Corte");

        grupoCorte.add(cortejRadioButton1);
        cortejRadioButton1.setText("1");
        cortejRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cortejRadioButton1ActionPerformed(evt);
            }
        });

        grupoCorte.add(cortejRadioButton2);
        cortejRadioButton2.setText("2");
        cortejRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cortejRadioButton2ActionPerformed(evt);
            }
        });

        grupoCorte.add(cortejRadioButton3);
        cortejRadioButton3.setText("3");
        cortejRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cortejRadioButton3ActionPerformed(evt);
            }
        });

        bloquearjButton.setText("Bloquear");
        bloquearjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bloquearjButtonActionPerformed(evt);
            }
        });

        cortejComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Default", "Femenino", "Masculino" }));
        cortejComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cortejComboBoxItemStateChanged(evt);
            }
        });

        nombrejLabel.setText("Nombre");

        telefonojLabel.setText("Teléfono");

        correojLabel.setText("Correo");

        domiciliojLabel.setText("Domicilio");

        domiciliojTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                domiciliojTextFieldActionPerformed(evt);
            }
        });

        totaljLabel.setText("Total $");

        totaljTextArea.setEditable(false);
        totaljTextArea.setColumns(20);
        totaljTextArea.setRows(5);
        totaljTextArea.setText("     -Peinado:\t\t"+totalPeinado+"\n\n"+"     -Tinte:\t\t"+totalTinte+"\n\n"+"     -Manicure:\t\t"+ totalManicure + "\n\n" + "     -Corte:\t\t"+totalCorte+"\n\n\n" + "   -Total:\t\t"+ total);
        jScrollPane2.setViewportView(totaljTextArea);

        eliminarjButton.setText("Eliminar");
        eliminarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarjButtonActionPerformed(evt);
            }
        });

        agnadirjButton.setText("Añadir");
        agnadirjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agnadirjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(fechajLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(horajLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(horajComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(cortejLabel)
                                .addGap(56, 56, 56))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(cortejComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)))
                        .addComponent(bloquearjButton)
                        .addGap(102, 102, 102))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(peinadojRadioButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(peinadojLabel)
                                .addGap(192, 192, 192)
                                .addComponent(tintejLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(peinadojRadioButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(peinadojRadioButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(peinadojRadioButtonD)
                                .addGap(75, 75, 75)
                                .addComponent(tintejRadioButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tintejRadioButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tintejRadioButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tintejRadioButtonD)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cortejRadioButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cortejRadioButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cortejRadioButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cortejRadioButtonD)
                        .addGap(187, 187, 187))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(857, 857, 857)
                        .addComponent(manicurejRadioButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(manicurejLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(manicurejRadioButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(manicurejRadioButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(manicurejRadioButtonD)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(nombrejLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(totaljLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(112, 112, 112)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(telefonojLabel)
                                    .addComponent(correojLabel)
                                    .addComponent(domiciliojLabel)))
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(nombrejTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(telefonojTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(correojTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(domiciliojTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(eliminarjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(agnadirjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(42, 42, 42)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(tintejLabel)
                                            .addComponent(peinadojLabel)
                                            .addComponent(manicurejLabel)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(bloquearjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(cortejLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(cortejComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(16, 16, 16)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cortejRadioButton1)
                                    .addComponent(cortejRadioButton2)
                                    .addComponent(cortejRadioButton3)
                                    .addComponent(cortejRadioButtonD)
                                    .addComponent(manicurejRadioButton1)
                                    .addComponent(manicurejRadioButton2)
                                    .addComponent(manicurejRadioButton3)
                                    .addComponent(manicurejRadioButtonD)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(peinadojRadioButton1)
                                    .addComponent(peinadojRadioButton2)
                                    .addComponent(peinadojRadioButton3)
                                    .addComponent(peinadojRadioButtonD)
                                    .addComponent(tintejRadioButton1)
                                    .addComponent(tintejRadioButton2)
                                    .addComponent(tintejRadioButton3)
                                    .addComponent(tintejRadioButtonD))))
                        .addGap(25, 25, 25))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(fechajLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(horajLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(horajComboBox, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nombrejLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nombrejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(telefonojLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(telefonojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(correojLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(correojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(domiciliojLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(domiciliojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(totaljLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(eliminarjButton, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                            .addComponent(agnadirjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 23, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void peinadojRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_peinadojRadioButton2ActionPerformed
        totalPeinado = PRECIO_PEINADO2; 
     
        total = (totalPeinado + totalTinte + totalManicure + totalCorte);
        totaljTextArea.setText("     -Peinado:\t\t"+totalPeinado+"\n\n"+"     -Tinte:\t\t"+totalTinte+"\n\n"+"     -Manicure:\t\t"+ totalManicure + "\n\n" + "     -Corte:\t\t"+totalCorte+"\n\n\n" + "   -Total:\t\t"+ total);
        // TODO add your handling code here:
        
    }//GEN-LAST:event_peinadojRadioButton2ActionPerformed

    private void tintejRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tintejRadioButton2ActionPerformed
        totalTinte = PRECIO_TINTE2; 
     
        total = (totalPeinado + totalTinte + totalManicure + totalCorte);
        totaljTextArea.setText("     -Peinado:\t\t"+totalPeinado+"\n\n"+"     -Tinte:\t\t"+totalTinte+"\n\n"+"     -Manicure:\t\t"+ totalManicure + "\n\n" + "     -Corte:\t\t"+totalCorte+"\n\n\n" + "   -Total:\t\t"+ total);
        // TODO add your handling code here:
    }//GEN-LAST:event_tintejRadioButton2ActionPerformed

    private void manicurejRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manicurejRadioButton2ActionPerformed
        totalManicure = PRECIO_MANICURE2; 
     
        total = (totalPeinado + totalTinte + totalManicure + totalCorte);
        totaljTextArea.setText("     -Peinado:\t\t"+totalPeinado+"\n\n"+"     -Tinte:\t\t"+totalTinte+"\n\n"+"     -Manicure:\t\t"+ totalManicure + "\n\n" + "     -Corte:\t\t"+totalCorte+"\n\n\n" + "   -Total:\t\t"+ total);
        // TODO add your handling code here:
    }//GEN-LAST:event_manicurejRadioButton2ActionPerformed

    private void cortejRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cortejRadioButton2ActionPerformed
        // TODO add your handling code here:
          if(sexoCorte.equals("Default")){
            cortejRadioButtonD.setSelected(true);  
            JOptionPane.showMessageDialog(null, "Por favor, seleccione un sexo primero");              
        }else if(sexoCorte.equals("Femenino")){
            totalCorte = PRECIO_CORTE_FEMENINO2; 
            
        total = (totalPeinado + totalTinte + totalManicure + totalCorte);
        totaljTextArea.setText("     -Peinado:\t\t"+totalPeinado+"\n\n"+"     -Tinte:\t\t"+totalTinte+"\n\n"+"     -Manicure:\t\t"+ totalManicure + "\n\n" + "     -Corte:\t\t"+totalCorte+"\n\n\n" + "   -Total:\t\t"+ total);
 
        }else{
            totalCorte = PRECIO_CORTE_MASCULINO2;  
     
        total = (totalPeinado + totalTinte + totalManicure + totalCorte);
        totaljTextArea.setText("     -Peinado:\t\t"+totalPeinado+"\n\n"+"     -Tinte:\t\t"+totalTinte+"\n\n"+"     -Manicure:\t\t"+ totalManicure + "\n\n" + "     -Corte:\t\t"+totalCorte+"\n\n\n" + "   -Total:\t\t"+ total);
 
        }
        
    }//GEN-LAST:event_cortejRadioButton2ActionPerformed

    private void eliminarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarjButtonActionPerformed
        // TODO add your handling code here:
         if(jDateChooser1.getDate()==null){
            JOptionPane.showMessageDialog(null, "Por favor, selecciona una fecha");
            banderaFecha = false;
        }else{
            banderaFecha = true;
        }
        
        if(validarHoraUnica() == true){
            JOptionPane.showMessageDialog(null, "Por favor, ingresa una hora existente");
            banderaHora = false;
        }else{
        
            banderaHora = true;
                    
        }
                
       
        if(banderaFecha == true && banderaHora == true){            
            if(filas==2){
                eliminarUnicoDato();
            }else{
                eliminarDatos();  
            }
            
            
            jTable1.setModel(new DefaultTableModel(data, columnas));
            horajComboBox.setSelectedItem(" ");
            peinadojRadioButtonD.setSelected(true);
            tintejRadioButtonD.setSelected(true);
            manicurejRadioButtonD.setSelected(true);
            cortejComboBox.setSelectedItem("Default");
            cortejRadioButtonD.setSelected(true);
            nombrejTextField.setText("");
            telefonojTextField.setText("");
            correojTextField.setText("");
            domiciliojTextField.setText("");
            total=0;
            totalCorte = PRECIO_CORTED;
            totalPeinado = PRECIO_PEINADOD;
            totalTinte = PRECIO_TINTED;
            totalManicure = PRECIO_MANICURED;
            totalCorte = PRECIO_CORTED;
            totaljTextArea.setText("     -Peinado:\t\t"+totalPeinado+"\n\n"+"     -Tinte:\t\t"+totalTinte+"\n\n"+"     -Manicure:\t\t"+ totalManicure + "\n\n" + "     -Corte:\t\t"+totalCorte+"\n\n\n" + "   -Total:\t\t"+ total);
           
            dataCambio = data;
            ++filas;            
            data = new String[filas][11];
            regresarValoresAData(data, dataCambio);
            fechas[indiceFechas] = data;
        }
    }//GEN-LAST:event_eliminarjButtonActionPerformed

    private void bloquearjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bloquearjButtonActionPerformed
        bloqueoButtonActionPerformed(evt);      // TODO add your handling code here:
    }//GEN-LAST:event_bloquearjButtonActionPerformed

    private void peinadojRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_peinadojRadioButton1ActionPerformed
        // TODO add your handling code here:
        totalPeinado = PRECIO_PEINADO1; 
     
        total = (totalPeinado + totalTinte + totalManicure + totalCorte);
        totaljTextArea.setText("     -Peinado:\t\t"+totalPeinado+"\n\n"+"     -Tinte:\t\t"+totalTinte+"\n\n"+"     -Manicure:\t\t"+ totalManicure + "\n\n" + "     -Corte:\t\t"+totalCorte+"\n\n\n" + "   -Total:\t\t"+ total);
        
    }//GEN-LAST:event_peinadojRadioButton1ActionPerformed

    private void peinadojRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_peinadojRadioButton3ActionPerformed
        totalPeinado = PRECIO_PEINADO3; 
     
        total = (totalPeinado + totalTinte + totalManicure + totalCorte);
        totaljTextArea.setText("     -Peinado:\t\t"+totalPeinado+"\n\n"+"     -Tinte:\t\t"+totalTinte+"\n\n"+"     -Manicure:\t\t"+ totalManicure + "\n\n" + "     -Corte:\t\t"+totalCorte+"\n\n\n" + "   -Total:\t\t"+ total);
        // TODO add your handling code here:
    }//GEN-LAST:event_peinadojRadioButton3ActionPerformed

    private void peinadojRadioButtonDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_peinadojRadioButtonDActionPerformed
        totalPeinado = PRECIO_PEINADOD; 
     
        total = (totalPeinado + totalTinte + totalManicure + totalCorte);
        totaljTextArea.setText("     -Peinado:\t\t"+totalPeinado+"\n\n"+"     -Tinte:\t\t"+totalTinte+"\n\n"+"     -Manicure:\t\t"+ totalManicure + "\n\n" + "     -Corte:\t\t"+totalCorte+"\n\n\n" + "   -Total:\t\t"+ total);
        // TODO add your handling code here:
    }//GEN-LAST:event_peinadojRadioButtonDActionPerformed

    private void tintejRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tintejRadioButton1ActionPerformed
        totalTinte = PRECIO_TINTE1; 
     
        total = (totalPeinado + totalTinte + totalManicure + totalCorte);
        totaljTextArea.setText("     -Peinado:\t\t"+totalPeinado+"\n\n"+"     -Tinte:\t\t"+totalTinte+"\n\n"+"     -Manicure:\t\t"+ totalManicure + "\n\n" + "     -Corte:\t\t"+totalCorte+"\n\n\n" + "   -Total:\t\t"+ total);
        // TODO add your handling code here:
    }//GEN-LAST:event_tintejRadioButton1ActionPerformed

    private void tintejRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tintejRadioButton3ActionPerformed
        totalTinte = PRECIO_TINTE3; 
     
        total = (totalPeinado + totalTinte + totalManicure + totalCorte);
        totaljTextArea.setText("     -Peinado:\t\t"+totalPeinado+"\n\n"+"     -Tinte:\t\t"+totalTinte+"\n\n"+"     -Manicure:\t\t"+ totalManicure + "\n\n" + "     -Corte:\t\t"+totalCorte+"\n\n\n" + "   -Total:\t\t"+ total);
        // TODO add your handling code here:
    }//GEN-LAST:event_tintejRadioButton3ActionPerformed

    private void tintejRadioButtonDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tintejRadioButtonDActionPerformed
        totalTinte = PRECIO_TINTED; 
     
        total = (totalPeinado + totalTinte + totalManicure + totalCorte);
        totaljTextArea.setText("     -Peinado:\t\t"+totalPeinado+"\n\n"+"     -Tinte:\t\t"+totalTinte+"\n\n"+"     -Manicure:\t\t"+ totalManicure + "\n\n" + "     -Corte:\t\t"+totalCorte+"\n\n\n" + "   -Total:\t\t"+ total);
        // TODO add your handling code here:
    }//GEN-LAST:event_tintejRadioButtonDActionPerformed

    private void manicurejRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manicurejRadioButton1ActionPerformed
        totalManicure = PRECIO_MANICURE1; 
     
        total = (totalPeinado + totalTinte + totalManicure + totalCorte);
        totaljTextArea.setText("     -Peinado:\t\t"+totalPeinado+"\n\n"+"     -Tinte:\t\t"+totalTinte+"\n\n"+"     -Manicure:\t\t"+ totalManicure + "\n\n" + "     -Corte:\t\t"+totalCorte+"\n\n\n" + "   -Total:\t\t"+ total);
        // TODO add your handling code here:
    }//GEN-LAST:event_manicurejRadioButton1ActionPerformed

    private void manicurejRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manicurejRadioButton3ActionPerformed
        totalManicure = PRECIO_MANICURE3; 
     
        total = (totalPeinado + totalTinte + totalManicure + totalCorte);
        totaljTextArea.setText("     -Peinado:\t\t"+totalPeinado+"\n\n"+"     -Tinte:\t\t"+totalTinte+"\n\n"+"     -Manicure:\t\t"+ totalManicure + "\n\n" + "     -Corte:\t\t"+totalCorte+"\n\n\n" + "   -Total:\t\t"+ total);
        // TODO add your handling code here:
    }//GEN-LAST:event_manicurejRadioButton3ActionPerformed

    private void manicurejRadioButtonDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manicurejRadioButtonDActionPerformed
        totalManicure = PRECIO_MANICURED; 
     
        total = (totalPeinado + totalTinte + totalManicure + totalCorte);
        totaljTextArea.setText("     -Peinado:\t\t"+totalPeinado+"\n\n"+"     -Tinte:\t\t"+totalTinte+"\n\n"+"     -Manicure:\t\t"+ totalManicure + "\n\n" + "     -Corte:\t\t"+totalCorte+"\n\n\n" + "   -Total:\t\t"+ total);
        // TODO add your handling code here:
    }//GEN-LAST:event_manicurejRadioButtonDActionPerformed

    private void cortejComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cortejComboBoxItemStateChanged
                // TODO add your handling code here:
                sexoCorte = cortejComboBox.getSelectedItem().toString();
                cortejRadioButtonD.setSelected(true);
                totalCorte = PRECIO_CORTED;
                
                total = (totalPeinado + totalTinte + totalManicure + totalCorte);
                totaljTextArea.setText("     -Peinado:\t\t"+totalPeinado+"\n\n"+"     -Tinte:\t\t"+totalTinte+"\n\n"+"     -Manicure:\t\t"+ totalManicure + "\n\n" + "     -Corte:\t\t"+totalCorte+"\n\n\n" + "   -Total:\t\t"+ total);
    }//GEN-LAST:event_cortejComboBoxItemStateChanged

    private void cortejRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cortejRadioButton1ActionPerformed
        // TODO add your handling code here:
        if(sexoCorte.equals("Default")){
            cortejRadioButtonD.setSelected(true);
            JOptionPane.showMessageDialog(null, "Por favor, seleccione un sexo primero");             
            
        }else if(sexoCorte.equals("Femenino")){
            totalCorte = PRECIO_CORTE_FEMENINO1; 
            
        total = (totalPeinado + totalTinte + totalManicure + totalCorte);
        totaljTextArea.setText("     -Peinado:\t\t"+totalPeinado+"\n\n"+"     -Tinte:\t\t"+totalTinte+"\n\n"+"     -Manicure:\t\t"+ totalManicure + "\n\n" + "     -Corte:\t\t"+totalCorte+"\n\n\n" + "   -Total:\t\t"+ total);
 
        }else{
            totalCorte = PRECIO_CORTE_MASCULINO1;  
     
        total = (totalPeinado + totalTinte + totalManicure + totalCorte);
        totaljTextArea.setText("     -Peinado:\t\t"+totalPeinado+"\n\n"+"     -Tinte:\t\t"+totalTinte+"\n\n"+"     -Manicure:\t\t"+ totalManicure + "\n\n" + "     -Corte:\t\t"+totalCorte+"\n\n\n" + "   -Total:\t\t"+ total);
 
        }
        
        
    }//GEN-LAST:event_cortejRadioButton1ActionPerformed

    private void cortejRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cortejRadioButton3ActionPerformed
        // TODO add your handling code here:
          if(sexoCorte.equals("Default")){
              cortejRadioButtonD.setSelected(true);
              JOptionPane.showMessageDialog(null, "Por favor, seleccione un sexo primero");  
        }else if(sexoCorte.equals("Femenino")){
            totalCorte = PRECIO_CORTE_FEMENINO3; 
            
        total = (totalPeinado + totalTinte + totalManicure + totalCorte);
        totaljTextArea.setText("     -Peinado:\t\t"+totalPeinado+"\n\n"+"     -Tinte:\t\t"+totalTinte+"\n\n"+"     -Manicure:\t\t"+ totalManicure + "\n\n" + "     -Corte:\t\t"+totalCorte+"\n\n\n" + "   -Total:\t\t"+ total);
 
        }else{
            totalCorte = PRECIO_CORTE_MASCULINO3;  
     
        total = (totalPeinado + totalTinte + totalManicure + totalCorte);
        totaljTextArea.setText("     -Peinado:\t\t"+totalPeinado+"\n\n"+"     -Tinte:\t\t"+totalTinte+"\n\n"+"     -Manicure:\t\t"+ totalManicure + "\n\n" + "     -Corte:\t\t"+totalCorte+"\n\n\n" + "   -Total:\t\t"+ total);
 
        }
        
    }//GEN-LAST:event_cortejRadioButton3ActionPerformed

    private void cortejRadioButtonDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cortejRadioButtonDActionPerformed
        // TODO add your handling code here:
          if(sexoCorte.equals("Default")){
            JOptionPane.showMessageDialog(null, "Por favor, seleccione un sexo primero");  
        }else if(sexoCorte.equals("Femenino")){
            totalCorte = PRECIO_CORTE_FEMENINOD; 
            
        total = (totalPeinado + totalTinte + totalManicure + totalCorte);
        totaljTextArea.setText("     -Peinado:\t\t"+totalPeinado+"\n\n"+"     -Tinte:\t\t"+totalTinte+"\n\n"+"     -Manicure:\t\t"+ totalManicure + "\n\n" + "     -Corte:\t\t"+totalCorte+"\n\n\n" + "   -Total:\t\t"+ total);
 
        }else{
            totalCorte = PRECIO_CORTE_MASCULINOD;  
     
        total = (totalPeinado + totalTinte + totalManicure + totalCorte);
        totaljTextArea.setText("     -Peinado:\t\t"+totalPeinado+"\n\n"+"     -Tinte:\t\t"+totalTinte+"\n\n"+"     -Manicure:\t\t"+ totalManicure + "\n\n" + "     -Corte:\t\t"+totalCorte+"\n\n\n" + "   -Total:\t\t"+ total);
 
        }
        
    }//GEN-LAST:event_cortejRadioButtonDActionPerformed

    private void domiciliojTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_domiciliojTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_domiciliojTextFieldActionPerformed

    private void agnadirjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agnadirjButtonActionPerformed
        // TODO add your handling code here:
        if(jDateChooser1.getDate()==null){
            JOptionPane.showMessageDialog(null, "Por favor, selecciona una fecha");
            banderaFecha = false;
        }else{
            banderaFecha = true;
        }
                
        if(nombrejTextField.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "Por favor, ingresa un nombre valido");
            banderaNombre = false;
        }else{
            banderaNombre = true;
        }
        
        if(total == 0){
            JOptionPane.showMessageDialog(null, "Por favor, selecciona un servicio");
            banderaTotal = false;
        }else{
            banderaTotal = true;
        }
        
        if(horajComboBox.getSelectedItem().toString().trim().equals("")){
            banderaHora = false;
            JOptionPane.showMessageDialog(null, "Por favor, ingresa una hora valida");
        }
        else if(validarHoraUnica() == false && banderaFecha == true && banderaNombre == true && banderaTotal == true){
            banderaHora = false;
            String botones[] = {"Sí", "No"};
            int eleccion = JOptionPane.showOptionDialog(this, "¿Desea modificar la cita registrada?", "Atención", 0, 0, null, botones, this);
            
            
            
            if(eleccion == JOptionPane.YES_OPTION){                
                modificarCita();
                
                
                //eliminar excedente en data
                dataCambio = data;
                filas = (filas -1);            
                data = new String[filas][11];
                regresarValoresADataDespuesDeEliminar(data, dataCambio);
                
                //mostrar tabla
                jTable1.setModel(new DefaultTableModel(data, columnas));
                
                //agnadir excedente en data
                dataCambio = data;
                ++filas;            
                data = new String[filas][11];
                regresarValoresAData(data, dataCambio);
            }
            else{
                JOptionPane.showMessageDialog(null, "Por favor, ingresa una hora valida");
            }
        }
        else if(validarHoraUnica() == false ){
                JOptionPane.showMessageDialog(null, "Por favor, ingresa una hora valida");
        
            
        }else{
        
            banderaHora = true;
                    
        }
        
        if(banderaFecha == true && banderaHora == true && banderaNombre == true && banderaTotal == true){            
            capturarDatosTabla(data);  
            ordenarData(data);
     
            jTable1.setModel(new DefaultTableModel(data, columnas));
            horajComboBox.setSelectedItem(" ");
            peinadojRadioButtonD.setSelected(true);
            tintejRadioButtonD.setSelected(true);
            manicurejRadioButtonD.setSelected(true);
            cortejComboBox.setSelectedItem("Default");
            cortejRadioButtonD.setSelected(true);
            nombrejTextField.setText("");
            telefonojTextField.setText("");
            correojTextField.setText("");
            domiciliojTextField.setText("");
            total=0;
            totalCorte = PRECIO_CORTED;
            totalPeinado = PRECIO_PEINADOD;
            totalTinte = PRECIO_TINTED;
            totalManicure = PRECIO_MANICURED;
            totalCorte = PRECIO_CORTED;
            totaljTextArea.setText("     -Peinado:\t\t"+totalPeinado+"\n\n"+"     -Tinte:\t\t"+totalTinte+"\n\n"+"     -Manicure:\t\t"+ totalManicure + "\n\n" + "     -Corte:\t\t"+totalCorte+"\n\n\n" + "   -Total:\t\t"+ total);
            dataCambio = data;
            ++filas;            
            data = new String[filas][11];
            regresarValoresAData(data, dataCambio);
            
            if(fechaNueva){
                fechas[indiceFechas] = data;
                ++cantidadFechas; 
                
                regresarFechas();
                fechaNueva = false;
            }else{
                fechas[indiceFechas] = data;
            }
        }
    }//GEN-LAST:event_agnadirjButtonActionPerformed

   
    private void regresarFechas(){
        String[][][] fechasCambio = fechas; 
        fechas = new String [cantidadFechas][filas][11];
        for(int i = 0; i < cantidadFechas-1; i++){
            fechas[i] = fechasCambio[i];
        }        
    }
    
    private void jDateChooser1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDateChooser1MouseClicked
                  // TODO add your handling code here:
    }//GEN-LAST:event_jDateChooser1MouseClicked

    private void jDateChooser1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jDateChooser1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jDateChooser1FocusLost

    private void jDateChooser1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDateChooser1MousePressed
        // TODO add your handling code here:
     
    }//GEN-LAST:event_jDateChooser1MousePressed

    private void jDateChooser1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDateChooser1PropertyChange
        // TODO add your handling code here:
        if(jDateChooser1.getDate() == null){
        }    
        
        else if(!fechaCapturada.equals(capturarFecha())){
            //System.out.println("Fecha distinta");
            fechaCapturada = capturarFecha();
            for(int i = 0; i < cantidadFechas; i++){
                if(fechas[i][0][0] == null){
                   // System.out.println("null");
                }
                else if(fechas[i][0][0].equals(capturarFecha()) ){
                    indiceFechas = i; 
                    
                    fechaNueva = false;
                    filas = fechas[i].length;
                   // System.out.println("length:" + filas) ;
                    break;
                }
                fechaNueva = true;
            }
            if(fechaNueva){
                indiceFechas = (cantidadFechas-1);
                filas=1;                 
            }
            data = fechas[indiceFechas];                    
            //elimina la fila extra
            dataCambio = data;               
            filas = (filas -1);            
            data = new String[filas][11];
            regresarValoresADataDespuesDeEliminar(data, dataCambio);
            
            //muestra la tabla sin esa fila extra
            jTable1.setModel(new DefaultTableModel(data, columnas));
            
            //añade de nuevo la fila extra
            dataCambio = data;
            ++filas;            
            data = new String[filas][11];
                    regresarValoresAData(data, dataCambio);
                    
            
            
            
            
            
            
        }else{
            
        }
        
    }//GEN-LAST:event_jDateChooser1PropertyChange

    private void bloqueoButtonActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
        
    
         java.awt.EventQueue.invokeLater(new Runnable(){
     public void run(){
        
         Estetica.inicioSesion.setVisible(true);
         Estetica.lista.setVisible(false);

          }
     });
     
    
    }


    private String capturarFecha(){
        String fecha;
          dia = Integer.toString(jDateChooser1.getCalendar().get(Calendar.DAY_OF_MONTH));
          mes = Integer.toString(jDateChooser1.getCalendar().get(Calendar.MONTH) + 1);
          agno = Integer.toString(jDateChooser1.getCalendar().get(Calendar.YEAR));
          
        fecha = (dia + "/" + mes + "/" + agno);
        return fecha;
    }
      private void modificarCita(){
          for(int i = 0; i < filas; i++){
             if(data[i][1].equals(horajComboBox.getSelectedItem().toString()) ){
                 
                data[i][0] = capturarFecha();
                data[i][1] = horajComboBox.getSelectedItem().toString();
                data[i][2] = nombrejTextField.getText();
                data[i][3] = telefonojTextField.getText();
                data[i][4] = correojTextField.getText();
                data[i][5] = domiciliojTextField.getText();
                data[i][6] = comprobarGrupoPeinadoSeleccionado();
                data[i][7] = comprobarGrupoTinteSeleccionado();
                data[i][8] = comprobarGrupoManicureSeleccionado();
                data[i][9] = comprobarGrupoCorteSeleccionado();
                data[i][10] = String.valueOf(total);
                break;
             } 
             
          }
      }
      private void capturarDatosTabla(String[][] data){

          data[filas-1][0] = capturarFecha();
          data[filas-1][1] = horajComboBox.getSelectedItem().toString();
          data[filas-1][2] = nombrejTextField.getText();
          data[filas-1][3] = telefonojTextField.getText();
          data[filas-1][4] = correojTextField.getText();
          data[filas-1][5] = domiciliojTextField.getText();
          data[filas-1][6] = comprobarGrupoPeinadoSeleccionado();
          data[filas-1][7] = comprobarGrupoTinteSeleccionado();
          data[filas-1][8] = comprobarGrupoManicureSeleccionado();
          data[filas-1][9] = comprobarGrupoCorteSeleccionado();
          data[filas-1][10] = String.valueOf(total);
      }
      private void eliminarDatos(){
         int k= 0;
          for(int i = 0; i < filas-1; i++){
            if(horajComboBox.getSelectedItem().toString().equals(data[i][1])){
                for(int j = i; j < filas-2; j++){
                   
                    data[j][0] = data[j+1][0];
                   
                    data[j][1] = data[j+1][1];
                   
                    data[j][2] = data[j+1][2];    
                   
                    data[j][3] = data[j+1][3];
                   
                    data[j][4] = data[j+1][4];
                   
                    data[j][5] = data[j+1][5];
                   
                    data[j][6] = data[j+1][6];
                   
                    data[j][7] = data[j+1][7];
                   
                    data[j][8] = data[j+1][8];
                   
                    data[j][9] = data[j+1][9];
                   
                    data[j][10] = data[j+1][10];
                   
                        
              
                }
                
                dataCambio = data;
                
                filas = (filas -2);            
                data = new String[filas][11];
                regresarValoresADataDespuesDeEliminar(data, dataCambio);
 
                break;
          }
         }
          
      }
      
       private void eliminarUnicoDato(){
         
                filas = 0;            
                data = new String[0][11];
                
  
      }
    
      private String comprobarGrupoPeinadoSeleccionado(){
          if(peinadojRadioButton1.isSelected()){
              return peinadojRadioButton1.getText();
          }else if(peinadojRadioButton2.isSelected()){
              return peinadojRadioButton2.getText();
          }else if(peinadojRadioButton3.isSelected()){
              return peinadojRadioButton3.getText();
          }else{
              return peinadojRadioButtonD.getText();
          }
      }
      
      private String comprobarGrupoTinteSeleccionado(){
          if(tintejRadioButton1.isSelected()){
              return tintejRadioButton1.getText();
          }else if(tintejRadioButton2.isSelected()){
              return tintejRadioButton2.getText();
          }else if(tintejRadioButton3.isSelected()){
              return tintejRadioButton3.getText();
          }else{
              return tintejRadioButtonD.getText();
          }
      }
      
      
      private String comprobarGrupoManicureSeleccionado(){
          if(manicurejRadioButton1.isSelected()){
              return manicurejRadioButton1.getText();
          }else if(manicurejRadioButton2.isSelected()){
              return manicurejRadioButton2.getText();
          }else if(manicurejRadioButton3.isSelected()){
              return manicurejRadioButton3.getText();
          }else{
              return manicurejRadioButtonD.getText();
          }
      }
      
      
      private String comprobarGrupoCorteSeleccionado(){
          if(cortejRadioButton1.isSelected()){
              return cortejRadioButton1.getText();
          }else if(cortejRadioButton2.isSelected()){
              return cortejRadioButton2.getText();
          }else if(cortejRadioButton3.isSelected()){
              return cortejRadioButton3.getText();
          }else{
              return cortejRadioButtonD.getText();
          }
      }
      
      private void regresarValoresAData(String[][] data, String [][] cambioData){
          for(int i = 0; i < filas-1; i++){
              data[i][0] = cambioData[i][0];
              data[i][1] = cambioData[i][1];
              data[i][2] = cambioData[i][2];
              data[i][3] = cambioData[i][3];
              data[i][4] = cambioData[i][4];
              data[i][5] = cambioData[i][5];
              data[i][6] = cambioData[i][6];
              data[i][7] = cambioData[i][7];
              data[i][8] = cambioData[i][8];
              data[i][9] = cambioData[i][9];
              data[i][10] = cambioData[i][10];
          }
      }
       private void regresarValoresADataDespuesDeEliminar(String[][] data, String [][] cambioData){
          for(int i = 0; i < filas; i++){
              data[i][0] = cambioData[i][0];
              data[i][1] = cambioData[i][1];
              data[i][2] = cambioData[i][2];
              data[i][3] = cambioData[i][3];
              data[i][4] = cambioData[i][4];
              data[i][5] = cambioData[i][5];
              data[i][6] = cambioData[i][6];
              data[i][7] = cambioData[i][7];
              data[i][8] = cambioData[i][8];
              data[i][9] = cambioData[i][9];
              data[i][10] = cambioData[i][10];
          }
      }
      private boolean validarHoraUnica(){
          for(int i = 0; i < filas-1; i++){
            if(horajComboBox.getSelectedItem().toString().trim().equals(data[i][1])) 
                return false;
          }
          return true;
      }
      
    private void ordenarData(String [][] data){
        String [][] dataAuxiliar = new String[filas][11];
        char digito1, digito2, digito3;
        int numero, numeroSiguiente;
        String cadenaNumero, cadenaNumeroSiguiente;
        for(int i = 0; i < filas-1; i++){
           
            for(int j = 0; j < filas-1; j++){
                digito1 = data[j][1].charAt(0);
                digito2 = data[j][1].charAt(1);
                digito3 = data[j][1].charAt(3);
                cadenaNumero = (String.valueOf(digito1) + String.valueOf(digito2) + String.valueOf(digito3));                
                numero = Integer.parseInt(cadenaNumero);
                
                digito1 = data[j+1][1].charAt(0);
                digito2 = data[j+1][1].charAt(1);
                digito3 = data[j+1][1].charAt(3);
                
                cadenaNumeroSiguiente = (String.valueOf(digito1) + String.valueOf(digito2) + String.valueOf(digito3));                
                numeroSiguiente = Integer.parseInt(cadenaNumeroSiguiente);
                
               // System.out.println("numero: " + numero + ", numeroSiguiente: " + numeroSiguiente + ".");
                if(numero > numeroSiguiente){
                    
                    
                    
                    dataAuxiliar[j][0] = data[j][0];
                    data[j][0] = data[j+1][0];
                    data[j+1][0] = dataAuxiliar[j][0];
                    
                    dataAuxiliar[j][1] = data[j][1];
                    data[j][1] = data[j+1][1];
                    data[j+1][1] = dataAuxiliar[j][1];

                    dataAuxiliar[j][2] = data[j][2];
                    data[j][2] = data[j+1][2];
                    data[j+1][2] = dataAuxiliar[j][2];

                    dataAuxiliar[j][3] = data[j][3];
                    data[j][3] = data[j+1][3];
                    data[j+1][3] = dataAuxiliar[j][3];

                    dataAuxiliar[j][4] = data[j][4];
                    data[j][4] = data[j+1][4];
                    data[j+1][4] = dataAuxiliar[j][4];

                    dataAuxiliar[j][5] = data[j][5];
                    data[j][5] = data[j+1][5];
                    data[j+1][5] = dataAuxiliar[j][5];

                    dataAuxiliar[j][6] = data[j][6];
                    data[j][6] = data[j+1][6];
                    data[j+1][6] = dataAuxiliar[j][6];

                    dataAuxiliar[j][7] = data[j][7];
                    data[j][7] = data[j+1][7];
                    data[j+1][7] = dataAuxiliar[j][7];

                    dataAuxiliar[j][8] = data[j][8];
                    data[j][8] = data[j+1][8];
                    data[j+1][8] = dataAuxiliar[j][8];

                    dataAuxiliar[j][9] = data[j][9];
                    data[j][9] = data[j+1][9];
                    data[j+1][9] = dataAuxiliar[j][9];

                    dataAuxiliar[j][10] = data[j][10];
                    data[j][10] = data[j+1][10];
                    data[j+1][10] = dataAuxiliar[j][10];

                }  
                  
            }
        }
      
    }
      
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agnadirjButton;
    private javax.swing.JButton bloquearjButton;
    private javax.swing.JLabel correojLabel;
    private javax.swing.JTextField correojTextField;
    private javax.swing.JComboBox<String> cortejComboBox;
    private javax.swing.JLabel cortejLabel;
    private javax.swing.JRadioButton cortejRadioButton1;
    private javax.swing.JRadioButton cortejRadioButton2;
    private javax.swing.JRadioButton cortejRadioButton3;
    private javax.swing.JRadioButton cortejRadioButtonD;
    private javax.swing.JLabel domiciliojLabel;
    private javax.swing.JTextField domiciliojTextField;
    private javax.swing.JButton eliminarjButton;
    private javax.swing.JLabel fechajLabel;
    private javax.swing.ButtonGroup grupoCorte;
    private javax.swing.ButtonGroup grupoManicure;
    private javax.swing.ButtonGroup grupoPeinado;
    private javax.swing.ButtonGroup grupoTinte;
    private javax.swing.JComboBox<String> horajComboBox;
    private javax.swing.JLabel horajLabel;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel manicurejLabel;
    private javax.swing.JRadioButton manicurejRadioButton1;
    private javax.swing.JRadioButton manicurejRadioButton2;
    private javax.swing.JRadioButton manicurejRadioButton3;
    private javax.swing.JRadioButton manicurejRadioButtonD;
    private javax.swing.JLabel nombrejLabel;
    private javax.swing.JTextField nombrejTextField;
    private javax.swing.JLabel peinadojLabel;
    private javax.swing.JRadioButton peinadojRadioButton1;
    private javax.swing.JRadioButton peinadojRadioButton2;
    private javax.swing.JRadioButton peinadojRadioButton3;
    private javax.swing.JRadioButton peinadojRadioButtonD;
    private javax.swing.JLabel telefonojLabel;
    private javax.swing.JTextField telefonojTextField;
    private javax.swing.JLabel tintejLabel;
    private javax.swing.JRadioButton tintejRadioButton1;
    private javax.swing.JRadioButton tintejRadioButton2;
    private javax.swing.JRadioButton tintejRadioButton3;
    private javax.swing.JRadioButton tintejRadioButtonD;
    private javax.swing.JLabel totaljLabel;
    private javax.swing.JTextArea totaljTextArea;
    // End of variables declaration//GEN-END:variables
    
    
    
}
